title: Eddie Hatfield
name: Eddie Hatfield's Site
author: Eddie Hatfield
author_nickname: Eddie Hatfield
email: edward.hatfield@tufts.edu
description: ""
baseurl: ""
url: "https://eddiehatfield.com"

github:
  repository_url: https://github.com/e-hat/e-hat/github.io
  branch: master

markdown: kramdown
kramdown:
  html_to_native: true
  syntax_highlighter: rouge
  input: GFM

highlighter: rouge

permalink: '/blog/:title'
post_dirs: false

plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      styles: ["post"]
      author: "Eddie Hatfield"
